version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: Verify VELO_CLIENT_VERSION
          command: |
            if [ "$VELO_CLIENT_VERSION" = "" ]; then
                circleci-agent step halt
                echo 'VELO_CLIENT_VERSION PARAM NOT SUPPLIED ... HALT BUILD'
            fi
      - checkout
      - run:
          name: Configure .env variables
          command: |
            make clone=1 key=${VELO_APIKEY} secret=${VELO_APISECRET} payor=${VELO_PAYORID} env
      - run:
          name: Init Docker Network
          command: |
            make network
      - run:
          name: Remove any existing db & redis container
          command: |
            docker rm /db
            docker rm /redis
      - run:
          name: Adjust the client dependency version
          command: |
            make version=${VELO_CLIENT_VERSION} setdep
      - run:
          name: Spin up the app
          command: |
            make up
      - run:
          name: Run E2E Tests
          command: |
            echo "Once up we should run tests"
      - run:
          name: Spin down the app
          command: |
            make down
      - run:
          name: Destroy the image
          command: |
            make destroy

workflows:
  version: 2
  build_test_release:
    jobs:
      - build
